accountId: "756007437776"
region: "ap-southeast-1"
awsProfile: "default"

vpc:
  name: "demo"
  config:
    cidrBlock: "10.23.0.0/16"
    tags:
      Name: "demo"
    tagsAll:
      Name: "demo"
  publicSubnets:
    - cidrBlock: "10.23.0.0/20"
    - cidrBlock: "10.23.16.0/20"
    - cidrBlock: "10.23.32.0/20"
  privateSubnets:
    - cidrBlock: "10.23.48.0/20"
    - cidrBlock: "10.23.64.0/20"
    - cidrBlock: "10.23.80.0/20"
  dbSubnets:
    - cidrBlock: "10.23.96.0/20"
    - cidrBlock: "10.23.112.0/20"
    - cidrBlock: "10.23.128.0/20"
    - cidrBlock: "10.23.144.0/20"

rds:
  name: "demo-cluster"
  engine: "aurora-mysql"
  family: "8.0"
  parameters:
    - key: character_set_server
      value: utf8